---
- name: Install rails gem
  become: yes
  become_user: geoblack
  shell: "source ~/.bashrc && gem install rails -v 5.2.3"
  tags:
    - install-geoblacklight
 
- name: Make folder in webroot for GeoBlacklight app
  become: yes
  file:
    state: directory
    path: "{{ geoblacklight_dir }}"
    owner: geoblack
    group: geoblack
  tags: install-geoblacklight

- name: Checkout custom GBL git repo
  become: yes
  become_user: geoblack
  git:
    dest: "{{ geoblacklight_dir }}/geodisy"
    clone: yes
    repo: "{{ geoblacklight_git_repo }}"
    force: yes
  tags:
    - install-geoblacklight

- name: Install Rails master.key file
  become: yes
  become_user: geoblack
  copy:
    src: secure_master.key
    dest: "{{ geoblacklight_dir }}/geodisy/config/master.key"
    owner: geoblack
    group: geoblack
    mode: 0600
  tags:
    - install-geoblacklight
    - test

- name: Create GeoBlacklight solr core
  become: yes
  become_user: solr
  shell: "/opt/solr/bin/solr create_core -c {{ geoblacklight_core_name }}"
  ignore_errors: yes # core already exists error
  tags:
    - install-geoblacklight

# Initialize GeoBlacklight Solr core as per Pauls email instructions
- name: Create a conf dir for geoblacklight-core
  become: yes
  become_user: solr
  file:
    state: directory
    path: "/var/solr/data/{{ geoblacklight_core_name }}/conf"
  tags:
    - install-geoblacklight

- name: Create a data dir for geoblacklight-core
  become: yes
  become_user: solr
  file:
    state: directory
    path: "/var/solr/data/{{ geoblacklight_core_name }}/data"
  tags:
    - install-geoblacklight

- name: Copy Solr core conf from geoblacklight project
  become: yes
  become_user: solr
  copy:
    remote_src: yes 
    src: "{{ geoblacklight_dir }}/geodisy/solr/conf/"
    dest: "/var/solr/data/{{ geoblacklight_core_name }}/conf/"
  tags:
    - install-geoblacklight

- name: Install blacklight.yml config file
  become: yes
  become_user: geoblack
  template:
    src: blacklight.yml.j2
    dest: "{{ geoblacklight_dir }}/geodisy/config/blacklight.yml"
  tags:
    - install-geoblacklight

- name: Install Geoblacklight systemd service file
  become: yes
  template:
    src: "geoblacklight.service.j2"
    dest: /etc/systemd/system/geoblacklight.service
  tags:
    - install-geoblacklight

- name: Enable/Start GeoBlacklight systemd service
  become: yes
  systemd:
    name: geoblacklight
    enabled: yes
    state: restarted
  tags:
    - install-geoblacklight
      
