---
# Ansible is not smart enough to use this variable hierarchy
# Look into this. It would keep the variables clean
#geoserver:
#  version: "2.16.0"
#  base_dir: "/opt/share/geoserver"
#  app_dir: "geoserver-{{ geoserver.version }}"
#  full_dir: "{{ geoserver.base_dir}}/{{ geoserver.app_dir }}"

# GeoServer
geoserver_version: "2.16.0"
geoserver_base_dir: "/opt/share/geoserver"
geoserver_app_dir: "geoserver-{{ geoserver_version }}"
geoserver_full_dir: "{{ geoserver_base_dir}}/{{ geoserver_app_dir }}"

# Apache Solr
solr:
  version: "8.3.0"
  location: "/solr"
  admin:
    user: "admin"
    password: "{{ vault.solr.admin.password }}"
