# Install Geoserver Tasks
---
- name: Provision environment with necessary packages
  become: yes
  yum:
    update_cache: yes
    state: present
    name: "{{ item }}"
  with_items:
   - unzip    
   - wget
  tags:
    - install-geoserver
    - packages

- name: Install Java 8
  become: yes
  yum:
    name: java-1.8.0-openjdk
    state: present
    update_cache: yes
  tags:
    - install-geoserver

- name: Create geoserver user
  become: yes
  user:
    name: geoserver
    state: present
    system: yes
  tags:
    - install-geoserver

- name: Create Geoserver directory
  become: yes
  file:
    state: directory
    path: "{{ geoserver_full_dir }}" 
    owner: "geoserver"
    group: "geoserver"
  tags:
    - install-geoserver

- name: Download GeoServer binary
  become: yes
  get_url:
    url: http://sourceforge.net/projects/geoserver/files/GeoServer/2.16.0/geoserver-2.16.0-bin.zip  
    dest: "{{ geoserver_base_dir }}/geoserver-2.16.0-bin.zip"
    owner: geoserver
    group: geoserver
    force: no
  tags: 
    - install-geoserver

- name: Unpack geoserver .zip
  become: yes
  unarchive:
    src: "{{ geoserver_base_dir }}/geoserver-2.16.0-bin.zip"
    dest: "{{ geoserver_base_dir }}" 
    owner: geoserver
    group: geoserver
  tags: 
    - install-geoserver

- name: Download GeoServer import plugin
  become: yes
  get_url:
    url: "https://downloads.sourceforge.net/project/geoserver/GeoServer/{{ geoserver_version }}/extensions/geoserver-{{ geoserver_version }}-importer-plugin.zip"
    dest: "{{ geoserver_base_dir }}"
    owner: geoserver
    group: geoserver
    force: no
  tags: 
    - install-geoserver

- name: Unpack GeoServer importer plugin
  become: yes
  unarchive:
    src: "{{ geoserver_base_dir }}/geoserver-{{ geoserver_version }}-importer-plugin.zip"
    dest: "{{ geoserver_full_dir }}/webapps/geoserver/WEB-INF/lib"
    owner: geoserver
    group: geoserver
  tags:
    - install-geoserver

- name: Install systemd service file
  become: yes
  template:
    src: geoserver.service.j2
    dest: /etc/systemd/system/geoserver.service
  tags: 
    - install-geoserver

- name: Daemon reload and start  geoserver systemd service
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: geoserver.service
    state: started
  tags: 
    - install-geoserver

