# Sets up all common requirements across all managed hosts
---
# When we merge this into a single Ansible repo, this task may already be accomplished
# in 'managed_hosts' role.
- name: Gather facts from both hosts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  when: hostvars[item]['ansible_default_ipv4'] is not defined
  with_items: "{{ groups['all'] }}"
  tags:
    - hosts

- name: Add internal IP addresses in /etc/hosts for all managed hosts 
  become: yes
  lineinfile:
    dest: /etc/hosts 
    regexp: ".*{{ item }}.*"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ item.split('.')[0] }}"
  with_items:
    - "{{ groups['geofront_host'] | default([]) }}"
    - "{{ groups['geoback_host'] | default([]) }}"
  tags:
    - hosts  

- name: Set time zone
  become: yes
  shell: "timedatectl set-timezone America/Regina"
  tags: hosts
