---
- name: Install system packages
  become: yes
  yum:
    name: curl
    state: present
    update_cache: yes
  tags:
    - install-node
    - install-yarn
    - packages

- name: Install node package repo
  become: yes
  shell:
    cmd: "curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -"
  tags:
    - install-node
    - packages 

- name: Install node package
  become: yes
  yum:
    name: nodejs
    state: present
    update_cache: yes
  tags:
    - install-node
    - packages

- name: Install yarn package repo
  become: yes
  shell:
    cmd: "curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"
  tags:
    - install-yarn
    - packages 

- name: Install yarn package
  become: yes
  yum:
    name: yarn
    state: present
    update_cache: yes
  tags:
    - install-yarn
    - packages
