# Frontend Tasks
---
- name: Install EPEL yum repo first
  become: yes
  yum:
    update_cache: yes
    state: present
    name: "epel-release"
  tags:
    - httpd
    - packages

- name: Install system packages
  become: yes
  yum:
    update_cache: yes
    state: present
    name: "{{ item }}"
  with_items:
    - mod_ssl
    - openssl
    - httpd
    - certbot
    - python2-certbot-apache
  tags:
    - httpd
    - packages
 
- name: Make server directory
  become: yes 
  file:
    state: directory
    path: "/var/www/{{ inventory_hostname }}/html"
    #owner:
    #group:
  tags:
    - httpd

- name: Install VirtualHost config
  become: yes
  template:
    src: "{{ group_names[0] }}.conf.j2"
    dest: "/etc/httpd/conf.d/{{ inventory_hostname }}.conf"
  tags:
    - httpd

- name: Allow Proxy to connect outbound
  become: yes
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  tags:
    - httpd

# Run Frontend Apache tasks
- name: Run Certbot
  become: yes
  shell: "certbot certonly --standalone -d {{ item }} -m {{ admin_email_address }} --agree-tos --non-interactive"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ inventory_hostname_alias }}"
  tags:
    - httpd
    - cert

- name: Install Apache systemd service
  become: yes
  systemd:
    name: httpd
    daemon_reload: yes
    enabled: yes
    state: started
  tags:
    - httpd

