---
apache:
  servername: "{{ inventory_hostname }}"
  serveralias: "{{ inventory_hostname_alias }}"
  geoserver_proxy: "{{ hostvars[groups['geoback_host'][0]]['inventory_hostname'] }}" 

geoblacklight_dir: "/var/www/geoblacklight"
geoblacklight_core_name: "geoblacklight-core"
geoblacklight_git_repo: "https://github.com/frdr-dfdr/geodisy-geoblacklight.git"

ruby_ver: "2.6.5"
rails_env: "production"

# Apache Solr
solr:
  version: "8.3.0"
  location: "/solr"
  admin:
    user: "admin"
    # vault-encrypted, but does solr also encrypt passwords?
    password: "yjGh8657QV5ryRDBiNe07MUPKrlrkW/fG4xLDnA5Pnw= SukmLiIEomRrC2XvvpSMQONs7CVXsw/nEVPX2jv+luM="
